# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "easyio"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Eichert"]
  s.date = "2012-02-24"
  s.description = "A gem for making IO tasks easy (at least for me)"
  s.email = "steve.eichert@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "easyio.gemspec",
    "lib/easyio.rb",
    "test/helper.rb",
    "test/test_easyio.rb"
  ]
  s.homepage = "http://github.com/eichert12/easyio"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A gem for making IO tasks easy (at least for me)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<aws-s3>, [">= 0.6.2"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<aws-s3>, [">= 0.6.2"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<aws-s3>, [">= 0.6.2"])
  end
end

