# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{easyio}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Eichert"]
  s.date = %q{2009-11-05}
  s.description = %q{A gem for making IO tasks easy (at least for me)}
  s.email = %q{steve.eichert@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "easyio.gemspec",
     "lib/easyio.rb",
     "test/helper.rb"
  ]
  s.homepage = %q{http://github.com/eichert12/easyio}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A gem for making IO tasks easy (at least for me)}
  s.test_files = [
    "test/easyio.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fastercsv>, [">= 1.5.0"])
      s.add_runtime_dependency(%q<aws-s3>, [">= 0.6.2"])
    else
      s.add_dependency(%q<fastercsv>, [">= 1.5.0"])
      s.add_dependency(%q<aws-s3>, [">= 0.6.2"])
    end
  else
    s.add_dependency(%q<fastercsv>, [">= 1.5.0"])
    s.add_dependency(%q<aws-s3>, [">= 0.6.2"])
  end
end

